using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;


namespace Pas.Common.Enums
{
    public enum City
    {
        Unknown = 0,
        Bagerhat = 1,
        Bandarban,
        Barguna,
        Barisal,
        Bhola,
        Bogra,
        Brahmanbaria,
        Chandpur,
        Chapai_Nawabganj,
        Chittagong,
        Chuadanga,
        Comilla,
        Coxs_Bazar,
        Dhaka,
        Dinajpur,
        Faridpur,
        Feni,
        Gaibandha,
        Gazipur,
        Gopalganj,
        Habiganj,
        Jaipurhat,
        Jamalpur,
        Jessore,
        Jhalokati,
        Jhenaidah,
        Khagrachhari,
        Khulna,
        Kishoreganj,
        Kurigram,
        Kushtia,
        Lakshmipur,
        Lalmonirhat,
        Madaripur,
        Magura,
        Manikganj,
        Maulvi_Bazar,
        Meherpur,
        Munshiganj,
        Mymensingh,
        Naogaon,
        Narail,
        Narayanganj,
        Narsingdi,
        Natore,
        Netrakona,
        Nilphamari,
        Noakhali,
        Pabna,
        Panchagarh,
        Patuakhali,
        Pirojpur,
        Rajbari,
        Rajshahi,
        Rangamati,
        Rangpur,
        Satkhira,
        Shariatpur,
        Sherpur,
        Sirajganj,
        Sunamganj,
        Sylhet,
        Tangail,
        Thakurgaon
    }
}
